### ISSUE TITLE
Not Working on OP7Pro

### ISSUE THREAD

**Issue by robbins** [ti0ma/oneplus-screen-shortcut#2]
Kirisakura Kernel (custom) on OB4. When I tap the QS tile nothing happens, and it's stuck on 90hz.

Don't think the kernel is breaking it, but idk I might just test with stock

**Comment by ti0ma** [comment]
Hi, I would need some further details about the issue you have.

1.- Have you grant the `WRITE_SECURE_SETTINGS` permission?
2.- Do any toast notification appear?
3.- Paste the output running this command via adb `adb shell settings list global | grep oneplus`

**Comment by robbins** [comment]
Thanks, worked after I granted write secure settings permission through adb as it never prompted me
